from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Tuple


def _read_text_file(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")[:300000]


def _sidecar_text(path: Path) -> Tuple[str, str] | None:
    candidates = [
        path.with_suffix(".search.txt"),
        Path(str(path) + ".search.txt"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return _read_text_file(candidate), f"sidecar:{candidate.name}"
    return None


def _pdf_text(path: Path) -> Tuple[str, str] | None:
    try:
        from pypdf import PdfReader  # type: ignore
    except Exception:
        return None
    try:
        reader = PdfReader(str(path))
        chunks = []
        for page in reader.pages[:20]:
            text = page.extract_text() or ""
            if text:
                chunks.append(text)
        text = "\n".join(chunks).strip()
        if text:
            return text[:300000], "pdf-text:pypdf"
    except Exception:
        return None
    return None


def _image_ocr_text(path: Path) -> Tuple[str, str] | None:
    """Optional OCR for image files using pytesseract when installed locally.

    The POC deliberately keeps this optional because Tesseract installation varies by platform.
    If pytesseract or the native Tesseract executable is unavailable, callers still get sidecar
    text generated by the sample data generator.
    """
    try:
        from PIL import Image
        import pytesseract  # type: ignore
    except Exception:
        return None
    try:
        with Image.open(path) as img:
            text = pytesseract.image_to_string(img)
        text = text.strip()
        if text:
            return text[:300000], "ocr:pytesseract"
    except Exception:
        return None
    return None


def extract_search_text(path: Path) -> Tuple[str, str]:
    """Return searchable text plus the extraction source used.

    The OCR behaviour is controlled by ``EEC_OCR_PROVIDER``:

    - ``sidecar``: use generated .search.txt sidecars first, then direct/PDF text; no native OCR.
    - ``tesseract``: try native pytesseract OCR for image files before sidecars.
    - ``auto``: sidecar/direct/PDF first, then native OCR if available.
    - ``none``: only direct text formats are indexed.
    """
    provider = os.getenv("EEC_OCR_PROVIDER", "auto").strip().lower()
    suffix = path.suffix.lower()

    if suffix in {".txt", ".json", ".csv", ".eml", ".md"}:
        return _read_text_file(path), "direct-text"

    if provider == "none":
        return "", "none"

    if provider == "tesseract" and suffix in {".png", ".jpg", ".jpeg", ".tif", ".tiff"}:
        ocr = _image_ocr_text(path)
        if ocr:
            return ocr

    sidecar = _sidecar_text(path)
    if sidecar:
        return sidecar

    if suffix == ".pdf":
        pdf = _pdf_text(path)
        if pdf:
            return pdf

    if provider in {"auto", "tesseract"} and suffix in {".png", ".jpg", ".jpeg", ".tif", ".tiff"}:
        ocr = _image_ocr_text(path)
        if ocr:
            return ocr

    return "", "none"
